name: Build and Push Docker Image

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.REGISTRY_AUTH_TOKEN }}

    - name: Extract branch name
      id: extract_branch
      run: echo "branch_name=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
    - name: Build and Push Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/sample-app-docker:${{ env.branch_name }} .
        docker push ghcr.io/${{ github.repository_owner }}/sample-app-docker:${{ env.branch_name }}
    - name: Checkout Infra Manifests
      uses: actions/checkout@v2
      with:
        repository: "marciok/pharrell-williams-manifests"
        ref: main
        token: ${{ secrets.MANIFESTS_REPO_TOKEN }}
    - name: Update Manifests
      uses: mikefarah/yq@master
      with:
        cmd: |
          mkdir manifests/overlay/${{ env.branch_name }}
          APP_NAME_PLACEHOLDER="${{ env.branch_name }}" yq '
            .patches[0].patch |= envsubst |
            .namePrefix |= envsubst |
            .labels[0].pairs.app |= envsubst |
            .images[0].newTag |= envsubst
          ' templates/app-kustomization.yml > manifests/overlay/${{ env.branch_name }}/app-kustomization.yml
          yq '
            .[0].value.host = "${{ env.branch_name }}.melhorbanco.digital" |
            .[0].value.http.paths[0].backend.service.name = "${{ env.branch_name }}-service"
          ' templates/patch.yml > manifests/overlay/${{ env.branch_name }}/patch.yml
          yq -i '.resources += "overlay/${{ env.branch_name }}"' manifests/kustomization.yml
          yq -i '.patches += { "path": "overlay/${{ env.branch_name }}/patch.yml", "target": { "kind": "Ingress", "name": "myapp-ingress" } }' manifests/kustomization.yml
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "New preview ${{ env.branch_name }}"
