name: Build and Push Docker Image

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.REGISTRY_AUTH_TOKEN }}

    - name: Extract branch name
      id: extract_branch
      run: echo "branch_name=${GITHUB_HEAD_REF}" >> $GITHUB_ENV

    - name: Build and Push Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/sample-app-docker:${{ env.branch_name }} .
        docker push ghcr.io/${{ github.repository_owner }}/sample-app-docker:${{ env.branch_name }}
