name: Teardown Preview
on:
    pull_request:
      branches: 
        - main
      types: [closed]

jobs:
  teardown-preview:
    runs-on: ubuntu-latest

    steps:
    - name: Extract branch name
      id: extract_branch
      run: echo "branch_name=${GITHUB_HEAD_REF}" >> $GITHUB_ENV